# Generated by Django 4.2 on 2023-04-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bargain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Наименование торга')),
                ('date', models.DateTimeField(verbose_name='Дата проведения')),
                ('placement_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата размещения')),
                ('source', models.CharField(blank=True, max_length=250, verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Торг',
                'verbose_name_plural': 'Торги',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Наименование документа')),
                ('placement_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата размещения')),
                ('source', models.CharField(blank=True, max_length=250, verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
